In [7]:
import pandas as pd

In [36]:
df = pd.read_csv("C:\\Users\\skill\\Play-code\\sql_mastery_for_data_analysis\\saudi_al_kabeer\\sales_transactions_clean.csv")

In [38]:
df.head(375)

,transaction_id,invoice_id,order_date,customer_id,product_id,city_id,quantity,unit_price,discount,total_amount
0,1,105555,2024-05-23,18113,23,10,5,437.19,0.00,2185.95
1,2,674001,2025-02-26,13218,73,9,2,447.01,0.00,894.02
2,3,331198,2025-06-13,6580,76,1,2,247.89,0.00,495.78
3,4,839149,2026-02-18,1900,8,8,2,690.15,0.00,1380.30
4,5,817010,2024-05-11,1244,7,5,2,120.74,0.15,205.26
...,...,...,...,...,...,...,...,...,...,...
370,371,375226,2024-03-21,10423,14,1,5,376.82,0.00,1884.10
371,372,998624,2025-06-01,18147,59,9,4,237.48,0.00,949.92
372,373,591671,2024-10-08,9543,59,8,1,237.48,0.00,237.48
373,374,623869,2025-01-23,17297,50,10,2,52.95,0.05,100.60
374,375,212462,2025-09-12,11790,28,1,2,257.41,0.05,489.08

In [25]:
df.count()

customer_id      200000
customer_name    200000
gender           200000
age              200000
age_group        200000
join_date        200000
dtype: int64

In [27]:
df.isnull().sum()

customer_id      0
customer_name    0
gender           0
age              0
age_group        0
join_date        0
dtype: int64

In [28]:
df = df.drop_duplicates()

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   customer_id    200000 non-null  int64
 1   customer_name  200000 non-null  object
 2   gender         200000 non-null  object
 3   age            200000 non-null  int64
 4   age_group      200000 non-null  object
 5   join_date      200000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 9.2+ MB

In [30]:
df['join_date'] = pd.to_datetime(df['join_date'], errors='coerce')

In [21]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['weekday'] = df['date'].dt.day_name()

In [33]:
df.head()

   customer_id       customer_name  gender  age age_group  join_date
0            1      Ziyad Al-Turki    Male   51     46-55 2021-11-17
1            2       Asma Al-Hazmi  Female   25     18-25 2022-04-16
2            3      Omar Al-Ghamdi    Male   32     26-35 2019-08-22
3            4  Abdulaziz Al-Bishi    Male   34     26-35 2023-06-18
4            5     Raed Al-Humaidi    Male   23     18-25 2020-03-11

In [34]:
df.isnull().sum()

customer_id      0
customer_name    0
gender           0
age              0
age_group        0
join_date        0
dtype: int64